// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// am1
arma::rowvec am1(const arma::vec& a, const arma::vec& T, const arma::vec& Y, const arma::vec& W, const arma::mat& X, const arma::vec& m);
RcppExport SEXP _swjm_am1(SEXP aSEXP, SEXP TSEXP, SEXP YSEXP, SEXP WSEXP, SEXP XSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(am1(a, T, Y, W, X, m));
    return rcpp_result_gen;
END_RCPP
}
// temLog
arma::rowvec temLog(const arma::vec& a, const arma::vec& b, const arma::mat& X, const arma::vec& Y, const arma::vec& Z, const arma::vec& D, const arma::vec& W);
RcppExport SEXP _swjm_temLog(SEXP aSEXP, SEXP bSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP DSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(temLog(a, b, X, Y, Z, D, W));
    return rcpp_result_gen;
END_RCPP
}
// temLog2
arma::rowvec temLog2(const arma::vec& yexa, const arma::mat& X, const arma::vec& Z, const arma::vec& D, const arma::vec& W);
RcppExport SEXP _swjm_temLog2(SEXP yexaSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP DSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type yexa(yexaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(temLog2(yexa, X, Z, D, W));
    return rcpp_result_gen;
END_RCPP
}
// reRate
arma::vec reRate(const arma::vec& T, const arma::vec& Y, const arma::vec& W, const arma::vec& T0);
RcppExport SEXP _swjm_reRate(SEXP TSEXP, SEXP YSEXP, SEXP WSEXP, SEXP T0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T0(T0SEXP);
    rcpp_result_gen = Rcpp::wrap(reRate(T, Y, W, T0));
    return rcpp_result_gen;
END_RCPP
}
// am2
arma::rowvec am2(const arma::vec& texa, const arma::vec& yexa, const arma::vec& T0, const arma::vec& T, const arma::vec& W, const arma::mat& X, const arma::vec& m);
RcppExport SEXP _swjm_am2(SEXP texaSEXP, SEXP yexaSEXP, SEXP T0SEXP, SEXP TSEXP, SEXP WSEXP, SEXP XSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type texa(texaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yexa(yexaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T0(T0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(am2(texa, yexa, T0, T, W, X, m));
    return rcpp_result_gen;
END_RCPP
}
// jfm_s0s1_cpp
Rcpp::List jfm_s0s1_cpp(const arma::vec& Y, const arma::mat& wt, const arma::vec& t_events, const arma::mat& idx_mat, const arma::mat& Z_pseudo, const arma::vec& coef);
RcppExport SEXP _swjm_jfm_s0s1_cpp(SEXP YSEXP, SEXP wtSEXP, SEXP t_eventsSEXP, SEXP idx_matSEXP, SEXP Z_pseudoSEXP, SEXP coefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type t_events(t_eventsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type idx_mat(idx_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_pseudo(Z_pseudoSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type coef(coefSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_s0s1_cpp(Y, wt, t_events, idx_mat, Z_pseudo, coef));
    return rcpp_result_gen;
END_RCPP
}
// jfm_s0s1_cf_cpp
Rcpp::List jfm_s0s1_cf_cpp(const arma::vec& Y, const arma::mat& wt, const arma::vec& t_events, const arma::mat& idx_mat, const arma::mat& Z_pseudo, const arma::mat& coef_mat, const arma::vec& cv_fold);
RcppExport SEXP _swjm_jfm_s0s1_cf_cpp(SEXP YSEXP, SEXP wtSEXP, SEXP t_eventsSEXP, SEXP idx_matSEXP, SEXP Z_pseudoSEXP, SEXP coef_matSEXP, SEXP cv_foldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type t_events(t_eventsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type idx_mat(idx_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_pseudo(Z_pseudoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coef_mat(coef_matSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cv_fold(cv_foldSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_s0s1_cf_cpp(Y, wt, t_events, idx_mat, Z_pseudo, coef_mat, cv_fold));
    return rcpp_result_gen;
END_RCPP
}
// jfm_score_cpp
arma::vec jfm_score_cpp(const arma::mat& idx_mat, const arma::vec& event_id, const arma::mat& Z_pseudo, const arma::mat& S1t, const arma::vec& S0t);
RcppExport SEXP _swjm_jfm_score_cpp(SEXP idx_matSEXP, SEXP event_idSEXP, SEXP Z_pseudoSEXP, SEXP S1tSEXP, SEXP S0tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type idx_mat(idx_matSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type event_id(event_idSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_pseudo(Z_pseudoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S1t(S1tSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type S0t(S0tSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_score_cpp(idx_mat, event_id, Z_pseudo, S1t, S0t));
    return rcpp_result_gen;
END_RCPP
}
// jfm_precompute_timeline
Rcpp::List jfm_precompute_timeline(const arma::vec& entry_times, const arma::vec& exit_times, const arma::ivec& is_last, const arma::vec& query_times, int query_before_enter);
RcppExport SEXP _swjm_jfm_precompute_timeline(SEXP entry_timesSEXP, SEXP exit_timesSEXP, SEXP is_lastSEXP, SEXP query_timesSEXP, SEXP query_before_enterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type entry_times(entry_timesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type exit_times(exit_timesSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type is_last(is_lastSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type query_times(query_timesSEXP);
    Rcpp::traits::input_parameter< int >::type query_before_enter(query_before_enterSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_precompute_timeline(entry_times, exit_times, is_last, query_times, query_before_enter));
    return rcpp_result_gen;
END_RCPP
}
// jfm_precompute_timeline_wt
Rcpp::List jfm_precompute_timeline_wt(const arma::vec& entry_times, const arma::vec& exit_times, const arma::ivec& is_last, const arma::vec& query_times, const arma::vec& wt_update_times, int query_before_enter);
RcppExport SEXP _swjm_jfm_precompute_timeline_wt(SEXP entry_timesSEXP, SEXP exit_timesSEXP, SEXP is_lastSEXP, SEXP query_timesSEXP, SEXP wt_update_timesSEXP, SEXP query_before_enterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type entry_times(entry_timesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type exit_times(exit_timesSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type is_last(is_lastSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type query_times(query_timesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wt_update_times(wt_update_timesSEXP);
    Rcpp::traits::input_parameter< int >::type query_before_enter(query_before_enterSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_precompute_timeline_wt(entry_times, exit_times, is_last, query_times, wt_update_times, query_before_enter));
    return rcpp_result_gen;
END_RCPP
}
// jfm_s0s1_fast_cpp
Rcpp::List jfm_s0s1_fast_cpp(const Rcpp::IntegerVector& tl_type, const Rcpp::IntegerVector& tl_idx, int tl_size, const arma::mat& Z_pseudo, const arma::vec& coef, int ne, int n);
RcppExport SEXP _swjm_jfm_s0s1_fast_cpp(SEXP tl_typeSEXP, SEXP tl_idxSEXP, SEXP tl_sizeSEXP, SEXP Z_pseudoSEXP, SEXP coefSEXP, SEXP neSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tl_type(tl_typeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tl_idx(tl_idxSEXP);
    Rcpp::traits::input_parameter< int >::type tl_size(tl_sizeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_pseudo(Z_pseudoSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< int >::type ne(neSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_s0s1_fast_cpp(tl_type, tl_idx, tl_size, Z_pseudo, coef, ne, n));
    return rcpp_result_gen;
END_RCPP
}
// jfm_s0s1_fast_cf_cpp
Rcpp::List jfm_s0s1_fast_cf_cpp(const Rcpp::IntegerVector& tl_type, const Rcpp::IntegerVector& tl_idx, int tl_size, const arma::mat& Z_pseudo, const arma::mat& coef_mat, const Rcpp::IntegerVector& subject_of_entry, const Rcpp::IntegerVector& cv_fold, int ne, int n);
RcppExport SEXP _swjm_jfm_s0s1_fast_cf_cpp(SEXP tl_typeSEXP, SEXP tl_idxSEXP, SEXP tl_sizeSEXP, SEXP Z_pseudoSEXP, SEXP coef_matSEXP, SEXP subject_of_entrySEXP, SEXP cv_foldSEXP, SEXP neSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tl_type(tl_typeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tl_idx(tl_idxSEXP);
    Rcpp::traits::input_parameter< int >::type tl_size(tl_sizeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_pseudo(Z_pseudoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coef_mat(coef_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type subject_of_entry(subject_of_entrySEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type cv_fold(cv_foldSEXP);
    Rcpp::traits::input_parameter< int >::type ne(neSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_s0s1_fast_cf_cpp(tl_type, tl_idx, tl_size, Z_pseudo, coef_mat, subject_of_entry, cv_fold, ne, n));
    return rcpp_result_gen;
END_RCPP
}
// jfm_s0s1_wt_fast_cpp
Rcpp::List jfm_s0s1_wt_fast_cpp(const Rcpp::IntegerVector& tl_type, const Rcpp::IntegerVector& tl_idx, int tl_size, const arma::mat& Z_pseudo, const Rcpp::IntegerVector& entry_subject, const arma::vec& coef, const arma::mat& wt_subj, int ne, int n);
RcppExport SEXP _swjm_jfm_s0s1_wt_fast_cpp(SEXP tl_typeSEXP, SEXP tl_idxSEXP, SEXP tl_sizeSEXP, SEXP Z_pseudoSEXP, SEXP entry_subjectSEXP, SEXP coefSEXP, SEXP wt_subjSEXP, SEXP neSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tl_type(tl_typeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tl_idx(tl_idxSEXP);
    Rcpp::traits::input_parameter< int >::type tl_size(tl_sizeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_pseudo(Z_pseudoSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type entry_subject(entry_subjectSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wt_subj(wt_subjSEXP);
    Rcpp::traits::input_parameter< int >::type ne(neSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_s0s1_wt_fast_cpp(tl_type, tl_idx, tl_size, Z_pseudo, entry_subject, coef, wt_subj, ne, n));
    return rcpp_result_gen;
END_RCPP
}
// jfm_s0s1_score_fused_cpp
Rcpp::List jfm_s0s1_score_fused_cpp(const Rcpp::IntegerVector& tl_type, const Rcpp::IntegerVector& tl_idx, int tl_size, const arma::mat& Z_pseudo, const arma::vec& coef, const Rcpp::IntegerVector& event_pseudo_idx, int ne, int n);
RcppExport SEXP _swjm_jfm_s0s1_score_fused_cpp(SEXP tl_typeSEXP, SEXP tl_idxSEXP, SEXP tl_sizeSEXP, SEXP Z_pseudoSEXP, SEXP coefSEXP, SEXP event_pseudo_idxSEXP, SEXP neSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tl_type(tl_typeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tl_idx(tl_idxSEXP);
    Rcpp::traits::input_parameter< int >::type tl_size(tl_sizeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_pseudo(Z_pseudoSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type event_pseudo_idx(event_pseudo_idxSEXP);
    Rcpp::traits::input_parameter< int >::type ne(neSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_s0s1_score_fused_cpp(tl_type, tl_idx, tl_size, Z_pseudo, coef, event_pseudo_idx, ne, n));
    return rcpp_result_gen;
END_RCPP
}
// jfm_cv_scores_batch_cpp
arma::vec jfm_cv_scores_batch_cpp(const Rcpp::IntegerVector& tl_type, const Rcpp::IntegerVector& tl_idx, int tl_size, const arma::mat& Z_pseudo, const arma::mat& coef_path, const Rcpp::IntegerVector& subject_of_entry, const Rcpp::IntegerVector& cv_fold, const Rcpp::IntegerVector& event_pseudo_idx, int ne, int n);
RcppExport SEXP _swjm_jfm_cv_scores_batch_cpp(SEXP tl_typeSEXP, SEXP tl_idxSEXP, SEXP tl_sizeSEXP, SEXP Z_pseudoSEXP, SEXP coef_pathSEXP, SEXP subject_of_entrySEXP, SEXP cv_foldSEXP, SEXP event_pseudo_idxSEXP, SEXP neSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tl_type(tl_typeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tl_idx(tl_idxSEXP);
    Rcpp::traits::input_parameter< int >::type tl_size(tl_sizeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_pseudo(Z_pseudoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coef_path(coef_pathSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type subject_of_entry(subject_of_entrySEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type cv_fold(cv_foldSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type event_pseudo_idx(event_pseudo_idxSEXP);
    Rcpp::traits::input_parameter< int >::type ne(neSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_cv_scores_batch_cpp(tl_type, tl_idx, tl_size, Z_pseudo, coef_path, subject_of_entry, cv_fold, event_pseudo_idx, ne, n));
    return rcpp_result_gen;
END_RCPP
}
// jfm_cv_scores_batch_cf_cpp
arma::vec jfm_cv_scores_batch_cf_cpp(const Rcpp::IntegerVector& tl_type, const Rcpp::IntegerVector& tl_idx, int tl_size, const arma::mat& Z_pseudo, const arma::mat& coef_array, int K_folds, const Rcpp::IntegerVector& subject_of_entry, const Rcpp::IntegerVector& cv_fold, const Rcpp::IntegerVector& event_pseudo_idx, int ne, int n);
RcppExport SEXP _swjm_jfm_cv_scores_batch_cf_cpp(SEXP tl_typeSEXP, SEXP tl_idxSEXP, SEXP tl_sizeSEXP, SEXP Z_pseudoSEXP, SEXP coef_arraySEXP, SEXP K_foldsSEXP, SEXP subject_of_entrySEXP, SEXP cv_foldSEXP, SEXP event_pseudo_idxSEXP, SEXP neSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tl_type(tl_typeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tl_idx(tl_idxSEXP);
    Rcpp::traits::input_parameter< int >::type tl_size(tl_sizeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_pseudo(Z_pseudoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coef_array(coef_arraySEXP);
    Rcpp::traits::input_parameter< int >::type K_folds(K_foldsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type subject_of_entry(subject_of_entrySEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type cv_fold(cv_foldSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type event_pseudo_idx(event_pseudo_idxSEXP);
    Rcpp::traits::input_parameter< int >::type ne(neSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_cv_scores_batch_cf_cpp(tl_type, tl_idx, tl_size, Z_pseudo, coef_array, K_folds, subject_of_entry, cv_fold, event_pseudo_idx, ne, n));
    return rcpp_result_gen;
END_RCPP
}
// jfm_score_fast_cpp
arma::vec jfm_score_fast_cpp(const Rcpp::IntegerVector& event_pseudo_idx, const arma::mat& Z_pseudo, const arma::mat& S1t, const arma::vec& S0t);
RcppExport SEXP _swjm_jfm_score_fast_cpp(SEXP event_pseudo_idxSEXP, SEXP Z_pseudoSEXP, SEXP S1tSEXP, SEXP S0tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type event_pseudo_idx(event_pseudo_idxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_pseudo(Z_pseudoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S1t(S1tSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type S0t(S0tSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_score_fast_cpp(event_pseudo_idx, Z_pseudo, S1t, S0t));
    return rcpp_result_gen;
END_RCPP
}
// jfm_build_pseudo_cpp
Rcpp::List jfm_build_pseudo_cpp(const arma::vec& t_start, const arma::vec& subj_id_raw, const arma::mat& Z_raw, const arma::vec& Y, const arma::vec& td, const arma::vec& td_id_raw, const arma::vec& tr, const arma::vec& tr_id_raw, const arma::vec& coef_death, const arma::vec& lambda0_d, double theta);
RcppExport SEXP _swjm_jfm_build_pseudo_cpp(SEXP t_startSEXP, SEXP subj_id_rawSEXP, SEXP Z_rawSEXP, SEXP YSEXP, SEXP tdSEXP, SEXP td_id_rawSEXP, SEXP trSEXP, SEXP tr_id_rawSEXP, SEXP coef_deathSEXP, SEXP lambda0_dSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type t_start(t_startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type subj_id_raw(subj_id_rawSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_raw(Z_rawSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type td(tdSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type td_id_raw(td_id_rawSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tr(trSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tr_id_raw(tr_id_rawSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type coef_death(coef_deathSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda0_d(lambda0_dSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_build_pseudo_cpp(t_start, subj_id_raw, Z_raw, Y, td, td_id_raw, tr, tr_id_raw, coef_death, lambda0_d, theta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_swjm_am1", (DL_FUNC) &_swjm_am1, 6},
    {"_swjm_temLog", (DL_FUNC) &_swjm_temLog, 7},
    {"_swjm_temLog2", (DL_FUNC) &_swjm_temLog2, 5},
    {"_swjm_reRate", (DL_FUNC) &_swjm_reRate, 4},
    {"_swjm_am2", (DL_FUNC) &_swjm_am2, 7},
    {"_swjm_jfm_s0s1_cpp", (DL_FUNC) &_swjm_jfm_s0s1_cpp, 6},
    {"_swjm_jfm_s0s1_cf_cpp", (DL_FUNC) &_swjm_jfm_s0s1_cf_cpp, 7},
    {"_swjm_jfm_score_cpp", (DL_FUNC) &_swjm_jfm_score_cpp, 5},
    {"_swjm_jfm_precompute_timeline", (DL_FUNC) &_swjm_jfm_precompute_timeline, 5},
    {"_swjm_jfm_precompute_timeline_wt", (DL_FUNC) &_swjm_jfm_precompute_timeline_wt, 6},
    {"_swjm_jfm_s0s1_fast_cpp", (DL_FUNC) &_swjm_jfm_s0s1_fast_cpp, 7},
    {"_swjm_jfm_s0s1_fast_cf_cpp", (DL_FUNC) &_swjm_jfm_s0s1_fast_cf_cpp, 9},
    {"_swjm_jfm_s0s1_wt_fast_cpp", (DL_FUNC) &_swjm_jfm_s0s1_wt_fast_cpp, 9},
    {"_swjm_jfm_s0s1_score_fused_cpp", (DL_FUNC) &_swjm_jfm_s0s1_score_fused_cpp, 8},
    {"_swjm_jfm_cv_scores_batch_cpp", (DL_FUNC) &_swjm_jfm_cv_scores_batch_cpp, 10},
    {"_swjm_jfm_cv_scores_batch_cf_cpp", (DL_FUNC) &_swjm_jfm_cv_scores_batch_cf_cpp, 11},
    {"_swjm_jfm_score_fast_cpp", (DL_FUNC) &_swjm_jfm_score_fast_cpp, 4},
    {"_swjm_jfm_build_pseudo_cpp", (DL_FUNC) &_swjm_jfm_build_pseudo_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_swjm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
