// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// am1
arma::rowvec am1(const arma::vec& a, const arma::vec& T, const arma::vec& Y, const arma::vec& W, const arma::mat& X, const arma::vec& m);
RcppExport SEXP _swjm_am1(SEXP aSEXP, SEXP TSEXP, SEXP YSEXP, SEXP WSEXP, SEXP XSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(am1(a, T, Y, W, X, m));
    return rcpp_result_gen;
END_RCPP
}
// temLog
arma::rowvec temLog(const arma::vec& a, const arma::vec& b, const arma::mat& X, const arma::vec& Y, const arma::vec& Z, const arma::vec& D, const arma::vec& W);
RcppExport SEXP _swjm_temLog(SEXP aSEXP, SEXP bSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP DSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(temLog(a, b, X, Y, Z, D, W));
    return rcpp_result_gen;
END_RCPP
}
// temLog2
arma::rowvec temLog2(const arma::vec& yexa, const arma::mat& X, const arma::vec& Z, const arma::vec& D, const arma::vec& W);
RcppExport SEXP _swjm_temLog2(SEXP yexaSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP DSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type yexa(yexaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(temLog2(yexa, X, Z, D, W));
    return rcpp_result_gen;
END_RCPP
}
// reRate
arma::vec reRate(const arma::vec& T, const arma::vec& Y, const arma::vec& W, const arma::vec& T0);
RcppExport SEXP _swjm_reRate(SEXP TSEXP, SEXP YSEXP, SEXP WSEXP, SEXP T0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T0(T0SEXP);
    rcpp_result_gen = Rcpp::wrap(reRate(T, Y, W, T0));
    return rcpp_result_gen;
END_RCPP
}
// am2
arma::rowvec am2(const arma::vec& texa, const arma::vec& yexa, const arma::vec& T0, const arma::vec& T, const arma::vec& W, const arma::mat& X, const arma::vec& m);
RcppExport SEXP _swjm_am2(SEXP texaSEXP, SEXP yexaSEXP, SEXP T0SEXP, SEXP TSEXP, SEXP WSEXP, SEXP XSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type texa(texaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yexa(yexaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T0(T0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(am2(texa, yexa, T0, T, W, X, m));
    return rcpp_result_gen;
END_RCPP
}
// jfm_s0s1_cpp
Rcpp::List jfm_s0s1_cpp(const arma::vec& Y, const arma::mat& wt, const arma::vec& t_events, const arma::mat& idx_mat, const arma::mat& Z_pseudo, const arma::vec& coef);
RcppExport SEXP _swjm_jfm_s0s1_cpp(SEXP YSEXP, SEXP wtSEXP, SEXP t_eventsSEXP, SEXP idx_matSEXP, SEXP Z_pseudoSEXP, SEXP coefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type t_events(t_eventsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type idx_mat(idx_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_pseudo(Z_pseudoSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type coef(coefSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_s0s1_cpp(Y, wt, t_events, idx_mat, Z_pseudo, coef));
    return rcpp_result_gen;
END_RCPP
}
// jfm_s0s1_cf_cpp
Rcpp::List jfm_s0s1_cf_cpp(const arma::vec& Y, const arma::mat& wt, const arma::vec& t_events, const arma::mat& idx_mat, const arma::mat& Z_pseudo, const arma::mat& coef_mat, const arma::vec& cv_fold);
RcppExport SEXP _swjm_jfm_s0s1_cf_cpp(SEXP YSEXP, SEXP wtSEXP, SEXP t_eventsSEXP, SEXP idx_matSEXP, SEXP Z_pseudoSEXP, SEXP coef_matSEXP, SEXP cv_foldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type t_events(t_eventsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type idx_mat(idx_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_pseudo(Z_pseudoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coef_mat(coef_matSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cv_fold(cv_foldSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_s0s1_cf_cpp(Y, wt, t_events, idx_mat, Z_pseudo, coef_mat, cv_fold));
    return rcpp_result_gen;
END_RCPP
}
// jfm_score_cpp
arma::vec jfm_score_cpp(const arma::mat& idx_mat, const arma::vec& event_id, const arma::mat& Z_pseudo, const arma::mat& S1t, const arma::vec& S0t);
RcppExport SEXP _swjm_jfm_score_cpp(SEXP idx_matSEXP, SEXP event_idSEXP, SEXP Z_pseudoSEXP, SEXP S1tSEXP, SEXP S0tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type idx_mat(idx_matSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type event_id(event_idSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_pseudo(Z_pseudoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S1t(S1tSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type S0t(S0tSEXP);
    rcpp_result_gen = Rcpp::wrap(jfm_score_cpp(idx_mat, event_id, Z_pseudo, S1t, S0t));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_swjm_am1", (DL_FUNC) &_swjm_am1, 6},
    {"_swjm_temLog", (DL_FUNC) &_swjm_temLog, 7},
    {"_swjm_temLog2", (DL_FUNC) &_swjm_temLog2, 5},
    {"_swjm_reRate", (DL_FUNC) &_swjm_reRate, 4},
    {"_swjm_am2", (DL_FUNC) &_swjm_am2, 7},
    {"_swjm_jfm_s0s1_cpp", (DL_FUNC) &_swjm_jfm_s0s1_cpp, 6},
    {"_swjm_jfm_s0s1_cf_cpp", (DL_FUNC) &_swjm_jfm_s0s1_cf_cpp, 7},
    {"_swjm_jfm_score_cpp", (DL_FUNC) &_swjm_jfm_score_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_swjm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
