# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

am1 <- function(a, T, Y, W, X, m) {
    .Call(`_swjm_am1`, a, T, Y, W, X, m)
}

temLog <- function(a, b, X, Y, Z, D, W) {
    .Call(`_swjm_temLog`, a, b, X, Y, Z, D, W)
}

temLog2 <- function(yexa, X, Z, D, W) {
    .Call(`_swjm_temLog2`, yexa, X, Z, D, W)
}

reRate <- function(T, Y, W, T0) {
    .Call(`_swjm_reRate`, T, Y, W, T0)
}

am2 <- function(texa, yexa, T0, T, W, X, m) {
    .Call(`_swjm_am2`, texa, yexa, T0, T, W, X, m)
}

jfm_s0s1_cpp <- function(Y, wt, t_events, idx_mat, Z_pseudo, coef) {
    .Call(`_swjm_jfm_s0s1_cpp`, Y, wt, t_events, idx_mat, Z_pseudo, coef)
}

jfm_s0s1_cf_cpp <- function(Y, wt, t_events, idx_mat, Z_pseudo, coef_mat, cv_fold) {
    .Call(`_swjm_jfm_s0s1_cf_cpp`, Y, wt, t_events, idx_mat, Z_pseudo, coef_mat, cv_fold)
}

jfm_score_cpp <- function(idx_mat, event_id, Z_pseudo, S1t, S0t) {
    .Call(`_swjm_jfm_score_cpp`, idx_mat, event_id, Z_pseudo, S1t, S0t)
}

