# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

am1 <- function(a, T, Y, W, X, m) {
    .Call(`_swjm_am1`, a, T, Y, W, X, m)
}

temLog <- function(a, b, X, Y, Z, D, W) {
    .Call(`_swjm_temLog`, a, b, X, Y, Z, D, W)
}

temLog2 <- function(yexa, X, Z, D, W) {
    .Call(`_swjm_temLog2`, yexa, X, Z, D, W)
}

reRate <- function(T, Y, W, T0) {
    .Call(`_swjm_reRate`, T, Y, W, T0)
}

am2 <- function(texa, yexa, T0, T, W, X, m) {
    .Call(`_swjm_am2`, texa, yexa, T0, T, W, X, m)
}

jfm_s0s1_cpp <- function(Y, wt, t_events, idx_mat, Z_pseudo, coef) {
    .Call(`_swjm_jfm_s0s1_cpp`, Y, wt, t_events, idx_mat, Z_pseudo, coef)
}

jfm_s0s1_cf_cpp <- function(Y, wt, t_events, idx_mat, Z_pseudo, coef_mat, cv_fold) {
    .Call(`_swjm_jfm_s0s1_cf_cpp`, Y, wt, t_events, idx_mat, Z_pseudo, coef_mat, cv_fold)
}

jfm_score_cpp <- function(idx_mat, event_id, Z_pseudo, S1t, S0t) {
    .Call(`_swjm_jfm_score_cpp`, idx_mat, event_id, Z_pseudo, S1t, S0t)
}

jfm_precompute_timeline <- function(entry_times, exit_times, is_last, query_times, query_before_enter = 0L) {
    .Call(`_swjm_jfm_precompute_timeline`, entry_times, exit_times, is_last, query_times, query_before_enter)
}

jfm_precompute_timeline_wt <- function(entry_times, exit_times, is_last, query_times, wt_update_times, query_before_enter = 0L) {
    .Call(`_swjm_jfm_precompute_timeline_wt`, entry_times, exit_times, is_last, query_times, wt_update_times, query_before_enter)
}

jfm_s0s1_fast_cpp <- function(tl_type, tl_idx, tl_size, Z_pseudo, coef, ne, n) {
    .Call(`_swjm_jfm_s0s1_fast_cpp`, tl_type, tl_idx, tl_size, Z_pseudo, coef, ne, n)
}

jfm_s0s1_fast_cf_cpp <- function(tl_type, tl_idx, tl_size, Z_pseudo, coef_mat, subject_of_entry, cv_fold, ne, n) {
    .Call(`_swjm_jfm_s0s1_fast_cf_cpp`, tl_type, tl_idx, tl_size, Z_pseudo, coef_mat, subject_of_entry, cv_fold, ne, n)
}

jfm_s0s1_wt_fast_cpp <- function(tl_type, tl_idx, tl_size, Z_pseudo, entry_subject, coef, wt_subj, ne, n) {
    .Call(`_swjm_jfm_s0s1_wt_fast_cpp`, tl_type, tl_idx, tl_size, Z_pseudo, entry_subject, coef, wt_subj, ne, n)
}

jfm_score_fast_cpp <- function(event_pseudo_idx, Z_pseudo, S1t, S0t) {
    .Call(`_swjm_jfm_score_fast_cpp`, event_pseudo_idx, Z_pseudo, S1t, S0t)
}

jfm_build_pseudo_cpp <- function(t_start, subj_id_raw, Z_raw, Y, td, td_id_raw, tr, tr_id_raw, coef_death, lambda0_d, theta) {
    .Call(`_swjm_jfm_build_pseudo_cpp`, t_start, subj_id_raw, Z_raw, Y, td, td_id_raw, tr, tr_id_raw, coef_death, lambda0_d, theta)
}

